added some string commands / name changes / split out dbm commands

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -12,7 +12,7 @@ ac_help=
 ac_default_prefix=/usr/local
 # Any additions from configure.in:
 ac_help="$ac_help
-  --with-tcl=DIR          Use Tcl source tree from
+  --with-tclconfigdir=DIR		Use tclConfig.sh from
 DIR"
 
 # Initialize some variables set by options.
@@ -523,35 +523,31 @@ fi
 
 # SCCS: @(#) configure.in 1.9 96/04/15 09:50:20
 
-#--------------------------------------------------------------------
-#	See if there was a command-line option for where Tcl is;  if
-#	not, assume that its top-level directory is a sibling of ours.
-#--------------------------------------------------------------------
+if test "${prefix}" = "NONE"; then
+    prefix=/usr/local
+    echo "setting prefix to: ${prefix}"
+fi
+if test "${exec_prefix}" = "NONE"; then
+    exec_prefix=$prefix
+    echo "setting exec-prefix to: ${exec_prefix}"
+fi
 
-# Check whether --with-tcl or --without-tcl was given.
-if test "${with_tcl+set}" = set; then
-  withval="$with_tcl"
-  TCL_SRC_DIR=$withval
+# Check whether --with-tclconfigdir or --without-tclconfigdir was given.
+if test "${with_tclconfigdir+set}" = set; then
+  withval="$with_tclconfigdir"
+  TCL_CONFIG_DIR=$withval
 else
-  TCL_SRC_DIR=`cd ../../tcl8.0; pwd`
+  TCL_CONFIG_DIR=`cd ${exec_prefix}/lib; pwd`
 fi
 
-if test ! -d $TCL_SRC_DIR; then
-    { echo "configure: error: Tcl directory $TCL_SRC_DIR doesn't exist" 1>&2; exit 1; }
-fi
 
-#--------------------------------------------------------------------
-#	Read in configuration information generated by Tcl for shared
-#	libraries, and arrange for it to be substituted into our
-#	Makefile.
-#--------------------------------------------------------------------
-
-if test ! -f $TCL_SRC_DIR/unix/tclConfig.sh; then
-    { echo "configure: error: File $TCL_SRC_DIR/unix/tclConfig.sh doesn't exist" 1>&2; exit 1; }
+if test ! -f $TCL_CONFIG_DIR/tclConfig.sh; then
+	{ echo "configure: error: $TCL_CONFIG_DIR/tclConfig.sh not found" 1>&2; exit 1; }
 fi
-echo "Using $TCL_SRC_DIR/unix/tclConfig.sh"
-file=$TCL_SRC_DIR/unix/tclConfig.sh
+echo "Using $TCL_CONFIG_DIR/tclConfig.sh"
+file=$TCL_CONFIG_DIR/tclConfig.sh
 . $file
+
 CC=$TCL_CC
 SHLIB_CFLAGS=$TCL_SHLIB_CFLAGS
 SHLIB_LD=$TCL_SHLIB_LD
@@ -560,6 +556,15 @@ SHLIB_SUFFIX=$TCL_SHLIB_SUFFIX
 SHLIB_VERSION=$TCL_SHLIB_VERSION
 TCL_LIBS=$TCL_LIBS
 TCL_VERSION=$TCL_VERSION
+
+
+
+
+
+
+
+
+
 
 
 
@@ -721,9 +726,17 @@ s%@SHLIB_LD_LIBS@%$SHLIB_LD_LIBS%g
 s%@SHLIB_SUFFIX@%$SHLIB_SUFFIX%g
 s%@SHLIB_VERSION@%$SHLIB_VERSION%g
 s%@TCL_BUILD_LIB_SPEC@%$TCL_BUILD_LIB_SPEC%g
+s%@TCL_LIB_SPEC@%$TCL_LIB_SPEC%g
 s%@TCL_LIBS@%$TCL_LIBS%g
 s%@TCL_VERSION@%$TCL_VERSION%g
 s%@TCL_SRC_DIR@%$TCL_SRC_DIR%g
+s%@TK_DEFS@%$TK_DEFS%g
+s%@TK_LIBS@%$TK_LIBS%g
+s%@TK_XINCLUDES@%$TK_XINCLUDES%g
+s%@TK_XLIBSW@%$TK_XLIBSW%g
+s%@TK_BUILD_LIB_SPEC@%$TK_BUILD_LIB_SPEC%g
+s%@TK_LIB_SPEC@%$TK_LIB_SPEC%g
+s%@TK_SRC_DIR@%$TK_SRC_DIR%g
 
 CEOF
 EOF
